//! Deterministic Fetch options and the exact command shared by preview and execution.

use crate::protocol::{CoreError, ErrorCode};
use serde::{Deserialize, Serialize};

/// Per-operation submodule policy; inheritance preserves the user's Git configuration.
#[derive(Debug, Clone, Copy, Default, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum GitFetchSubmodules {
    #[default]
    Inherit,
    No,
    OnDemand,
    Yes,
}

/// Tag transfer policy; inheritance leaves repository and remote configuration effective.
#[derive(Debug, Clone, Copy, Default, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum GitFetchTags {
    #[default]
    Inherit,
    All,
    None,
    /// Also removes local tags absent from the fetched remote.
    Prune,
}

/// Structured Fetch choices. These never write repository or global configuration.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", default, deny_unknown_fields)]
pub struct GitFetchOptions {
    /// A configured remote name; null selects all remotes, preserving the legacy scope.
    pub remote: Option<String>,
    /// Remove stale remote-tracking references; false explicitly overrides fetch.prune.
    pub prune: bool,
    pub submodules: GitFetchSubmodules,
    pub tags: GitFetchTags,
}

impl Default for GitFetchOptions {
    fn default() -> Self {
        Self {
            remote: None,
            prune: true,
            submodules: GitFetchSubmodules::Inherit,
            tags: GitFetchTags::Inherit,
        }
    }
}

/// Pure command-preview input; no repository, credentials, or process is accessed.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GitFetchPlanRequest {
    #[serde(default)]
    pub options: GitFetchOptions,
}

/// Planned arguments are generated by the same function used immediately before Fetch.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GitFetchPlan {
    pub options: GitFetchOptions,
    /// Exact argument vector, excluding the executable; not evidence that Git has started.
    pub arguments: Vec<String>,
}

/// Validates structured choices and builds temporary presentation configuration.
pub fn plan(request: GitFetchPlanRequest) -> Result<GitFetchPlan, CoreError> {
    let arguments = arguments(&request.options)?;
    Ok(GitFetchPlan {
        options: request.options,
        arguments,
    })
}

pub(super) fn arguments(options: &GitFetchOptions) -> Result<Vec<String>, CoreError> {
    if let Some(remote) = &options.remote {
        // Reject option, URL, and absolute-path syntax while allowing remote
        // names with punctuation. Execution verifies the name is configured.
        if remote.is_empty()
            || remote.starts_with(['-', '/', '.'])
            || remote.ends_with(['/', '.'])
            || remote.contains("..")
            || remote.contains("//")
            || remote.contains("@{")
            || remote.split('/').any(|part| part.ends_with(".lock"))
            || remote
                .chars()
                .any(|c| c.is_control() || c.is_whitespace() || ":\\~^?*[".contains(c))
        {
            return Err(CoreError::new(
                ErrorCode::InvalidRequest,
                "Fetch requires a remote name",
            ));
        }
    }
    // These flags affect this invocation only. Authentication, proxy, signing,
    // and submodule configuration remain inherited unless explicitly selected.
    let mut arguments = vec![
        "--no-pager".into(),
        "-c".into(),
        "color.ui=false".into(),
        "-c".into(),
        "core.quotepath=false".into(),
        "fetch".into(),
        "--progress".into(),
    ];
    if options.remote.is_none() {
        arguments.push("--all".into());
    }
    arguments.push(
        if options.prune {
            "--prune"
        } else {
            "--no-prune"
        }
        .into(),
    );
    match options.tags {
        GitFetchTags::Inherit => {}
        GitFetchTags::All => arguments.push("--tags".into()),
        GitFetchTags::None => arguments.push("--no-tags".into()),
        GitFetchTags::Prune => {
            if !options.prune {
                return Err(CoreError::new(
                    ErrorCode::InvalidRequest,
                    "Tag pruning requires pruning stale references",
                ));
            }
            arguments.push("--prune-tags".into());
        }
    }
    match options.submodules {
        GitFetchSubmodules::Inherit => {}
        GitFetchSubmodules::No => arguments.push("--recurse-submodules=no".into()),
        GitFetchSubmodules::OnDemand => arguments.push("--recurse-submodules=on-demand".into()),
        GitFetchSubmodules::Yes => arguments.push("--recurse-submodules=yes".into()),
    }
    if let Some(remote) = &options.remote {
        arguments.extend(["--".into(), remote.clone()]);
    }
    Ok(arguments)
}

#[cfg(test)]
mod tests {
    use serde_json::{json, Value};

    fn fixture() -> Value {
        serde_json::from_str(include_str!(
            "../../../../shared/fixtures/git/fetch-plan-v1.json"
        ))
        .unwrap()
    }

    fn request(payload: Value) -> Value {
        serde_json::from_str(&crate::execute_json(
            &json!({
                "id": "fetch-plan-test", "command": "git.fetchPlan", "payload": payload
            })
            .to_string(),
        ))
        .unwrap()
    }

    #[test]
    fn fetch_plans_match_shared_choices_without_accessing_a_repository() {
        for case in fixture()["cases"].as_array().unwrap() {
            let response = request(json!({"options": case["options"]}));
            assert_eq!(response["ok"], true, "{response}");
            assert_eq!(response["data"]["options"], case["expectedOptions"]);
            assert_eq!(response["data"]["arguments"], case["arguments"]);
            let options = serde_json::from_value(case["expectedOptions"].clone()).unwrap();
            assert_eq!(
                serde_json::to_value(super::arguments(&options).unwrap()).unwrap(),
                case["arguments"]
            );
        }
    }

    #[test]
    fn fetch_rejects_sources_and_arguments_in_the_remote_name_field() {
        for remote in fixture()["invalidRemotes"].as_array().unwrap() {
            let response = request(json!({"options": {"remote": remote}}));
            assert_eq!(
                response["error"]["code"], "invalid_request",
                "{remote}: {response}"
            );
        }
    }

    #[test]
    fn fetch_rejects_unknown_settings_instead_of_silently_ignoring_them() {
        for options in [
            json!({"prune": "false"}),
            json!({"submodules": "sometimes"}),
            json!({"arguments": ["--force"]}),
            json!({"credentialHelper": ""}),
        ] {
            assert_eq!(
                request(json!({"options": options}))["error"]["code"],
                "invalid_request"
            );
        }
        // Misplaced options must fail before repository lookup or any mutation.
        let response: Value = serde_json::from_str(&crate::execute_json(&json!({
            "command": "git.write", "payload": {"root": "", "operation": "commit", "fetchOptions": {}}
        }).to_string())).unwrap();
        assert_eq!(
            response["error"]["message"],
            "Fetch options require a fetch operation"
        );
    }
}
