// AUTO-GENERATED by scripts/generate-idea-icons.ts — do not edit by hand.
// Mapping source: scripts/idea-icon-mappings.json (paths relative to the
// intellij-community platform/icons/src checkout passed via --source).
// Keys are icon export display names resolved by createIconComponent.

import arrowClockwiseLight from "./idea/expui/general/redo.svg?url";
import arrowClockwiseDark from "./idea/expui/general/redo_dark.svg?url";
import arrowCounterClockwiseLight from "./idea/expui/general/undo.svg?url";
import arrowCounterClockwiseDark from "./idea/expui/general/undo_dark.svg?url";
import bellLight from "./idea/expui/toolwindows/notifications.svg?url";
import bellDark from "./idea/expui/toolwindows/notifications_dark.svg?url";
import bugLight from "./idea/expui/run/debug.svg?url";
import bugDark from "./idea/expui/run/debug_dark.svg?url";
import caretDownLight from "./idea/expui/general/chevronDown.svg?url";
import caretDownDark from "./idea/expui/general/chevronDown_dark.svg?url";
import caretLeftLight from "./idea/expui/general/chevronLeft.svg?url";
import caretLeftDark from "./idea/expui/general/chevronLeft_dark.svg?url";
import caretRightLight from "./idea/expui/general/chevronRight.svg?url";
import caretRightDark from "./idea/expui/general/chevronRight_dark.svg?url";
import caretUpLight from "./idea/expui/general/chevronUp.svg?url";
import caretUpDark from "./idea/expui/general/chevronUp_dark.svg?url";
import checkCircleLight from "./idea/expui/general/successDialog.svg?url";
import checkCircleDark from "./idea/expui/general/successDialog_dark.svg?url";
import checkLight from "./idea/expui/general/greenCheckmark.svg?url";
import checkDark from "./idea/expui/general/greenCheckmark_dark.svg?url";
import chevronDownLight from "./idea/expui/general/chevronDown.svg?url";
import chevronDownDark from "./idea/expui/general/chevronDown_dark.svg?url";
import chevronLeftLight from "./idea/expui/general/chevronLeft.svg?url";
import chevronLeftDark from "./idea/expui/general/chevronLeft_dark.svg?url";
import chevronRightLight from "./idea/expui/general/chevronRight.svg?url";
import chevronRightDark from "./idea/expui/general/chevronRight_dark.svg?url";
import chevronUpLight from "./idea/expui/general/chevronUp.svg?url";
import chevronUpDark from "./idea/expui/general/chevronUp_dark.svg?url";
import clockCounterClockwiseLight from "./idea/expui/general/history.svg?url";
import clockCounterClockwiseDark from "./idea/expui/general/history_dark.svg?url";
import copyLight from "./idea/expui/general/copy.svg?url";
import copyDark from "./idea/expui/general/copy_dark.svg?url";
import dotsThreeLight from "./idea/expui/general/moreHorizontal.svg?url";
import dotsThreeDark from "./idea/expui/general/moreHorizontal_dark.svg?url";
import downloadLight from "./idea/expui/general/download.svg?url";
import downloadDark from "./idea/expui/general/download_dark.svg?url";
import fileLight from "./idea/fileTypes/text.svg?url";
import filePlusLight from "./idea/expui/actions/addFile.svg?url";
import filePlusDark from "./idea/expui/actions/addFile_dark.svg?url";
import fileTextLight from "./idea/fileTypes/text.svg?url";
import floppyDiskLight from "./idea/expui/general/save.svg?url";
import floppyDiskDark from "./idea/expui/general/save_dark.svg?url";
import folderLight from "./idea/expui/nodes/folder.svg?url";
import folderDark from "./idea/expui/nodes/folder_dark.svg?url";
import folderPlusLight from "./idea/expui/actions/newFolder.svg?url";
import folderPlusDark from "./idea/expui/actions/newFolder_dark.svg?url";
import funnelLight from "./idea/expui/general/filter.svg?url";
import funnelDark from "./idea/expui/general/filter_dark.svg?url";
import gearLight from "./idea/expui/general/settings.svg?url";
import gearDark from "./idea/expui/general/settings_dark.svg?url";
import gitBranchLight from "./idea/vcs/branch.svg?url";
import gitBranchDark from "./idea/vcs/branch_dark.svg?url";
import gitCommitLight from "./idea/expui/vcs/commit.svg?url";
import gitCommitDark from "./idea/expui/vcs/commit_dark.svg?url";
import gitDiffLight from "./idea/expui/vcs/diff.svg?url";
import gitDiffDark from "./idea/expui/vcs/diff_dark.svg?url";
import gitMergeLight from "./idea/expui/vcs/merge.svg?url";
import gitMergeDark from "./idea/expui/vcs/merge_dark.svg?url";
import infoLight from "./idea/expui/general/informationDialog.svg?url";
import infoDark from "./idea/expui/general/informationDialog_dark.svg?url";
import keyboardLight from "./idea/expui/general/keyboard.svg?url";
import keyboardDark from "./idea/expui/general/keyboard_dark.svg?url";
import lockLight from "./idea/expui/general/locked.svg?url";
import lockDark from "./idea/expui/general/locked_dark.svg?url";
import lockOpenLight from "./idea/expui/general/unlocked.svg?url";
import lockOpenDark from "./idea/expui/general/unlocked_dark.svg?url";
import magnifyingGlassLight from "./idea/expui/general/search.svg?url";
import magnifyingGlassDark from "./idea/expui/general/search_dark.svg?url";
import minusLight from "./idea/expui/general/remove.svg?url";
import minusDark from "./idea/expui/general/remove_dark.svg?url";
import openExternalLight from "./idea/expui/ide/externalLink.svg?url";
import openExternalDark from "./idea/expui/ide/externalLink_dark.svg?url";
import pauseLight from "./idea/expui/run/pause.svg?url";
import pauseDark from "./idea/expui/run/pause_dark.svg?url";
import pencilLight from "./idea/expui/general/edit.svg?url";
import pencilDark from "./idea/expui/general/edit_dark.svg?url";
import playLight from "./idea/expui/run/run.svg?url";
import playDark from "./idea/expui/run/run_dark.svg?url";
import plusLight from "./idea/expui/general/add.svg?url";
import plusDark from "./idea/expui/general/add_dark.svg?url";
import pushPinLight from "./idea/expui/general/pin.svg?url";
import pushPinDark from "./idea/expui/general/pin_dark.svg?url";
import questionLight from "./idea/expui/general/questionDialog.svg?url";
import questionDark from "./idea/expui/general/questionDialog_dark.svg?url";
import refreshLight from "./idea/expui/general/refresh.svg?url";
import refreshDark from "./idea/expui/general/refresh_dark.svg?url";
import stopLight from "./idea/expui/run/stop.svg?url";
import stopDark from "./idea/expui/run/stop_dark.svg?url";
import trashLight from "./idea/expui/general/delete.svg?url";
import trashDark from "./idea/expui/general/delete_dark.svg?url";
import uploadLight from "./idea/expui/general/upload.svg?url";
import uploadDark from "./idea/expui/general/upload_dark.svg?url";
import userLight from "./idea/expui/general/user.svg?url";
import userDark from "./idea/expui/general/user_dark.svg?url";
import warningCircleLight from "./idea/expui/general/warningDialog.svg?url";
import warningCircleDark from "./idea/expui/general/warningDialog_dark.svg?url";
import warningLight from "./idea/expui/general/warningDialog.svg?url";
import warningDark from "./idea/expui/general/warningDialog_dark.svg?url";
import xCircleLight from "./idea/expui/general/errorDialog.svg?url";
import xCircleDark from "./idea/expui/general/errorDialog_dark.svg?url";
import xLight from "./idea/expui/general/close.svg?url";
import xDark from "./idea/expui/general/close_dark.svg?url";

export interface IdeaIconAsset {
  light: string;
  dark: string;
}

export const ideaIconAssets: Record<string, IdeaIconAsset> = {
  ArrowClockwiseIcon: { light: arrowClockwiseLight, dark: arrowClockwiseDark },
  ArrowCounterClockwiseIcon: { light: arrowCounterClockwiseLight, dark: arrowCounterClockwiseDark },
  BellIcon: { light: bellLight, dark: bellDark },
  BugIcon: { light: bugLight, dark: bugDark },
  CaretDownIcon: { light: caretDownLight, dark: caretDownDark },
  CaretLeftIcon: { light: caretLeftLight, dark: caretLeftDark },
  CaretRightIcon: { light: caretRightLight, dark: caretRightDark },
  CaretUpIcon: { light: caretUpLight, dark: caretUpDark },
  CheckCircleIcon: { light: checkCircleLight, dark: checkCircleDark },
  CheckIcon: { light: checkLight, dark: checkDark },
  ChevronDownIcon: { light: chevronDownLight, dark: chevronDownDark },
  ChevronLeftIcon: { light: chevronLeftLight, dark: chevronLeftDark },
  ChevronRightIcon: { light: chevronRightLight, dark: chevronRightDark },
  ChevronUpIcon: { light: chevronUpLight, dark: chevronUpDark },
  ClockCounterClockwiseIcon: { light: clockCounterClockwiseLight, dark: clockCounterClockwiseDark },
  CopyIcon: { light: copyLight, dark: copyDark },
  DotsThreeIcon: { light: dotsThreeLight, dark: dotsThreeDark },
  DownloadIcon: { light: downloadLight, dark: downloadDark },
  FileIcon: { light: fileLight, dark: fileLight },
  FilePlusIcon: { light: filePlusLight, dark: filePlusDark },
  FileTextIcon: { light: fileTextLight, dark: fileTextLight },
  FloppyDiskIcon: { light: floppyDiskLight, dark: floppyDiskDark },
  FolderIcon: { light: folderLight, dark: folderDark },
  FolderPlusIcon: { light: folderPlusLight, dark: folderPlusDark },
  FunnelIcon: { light: funnelLight, dark: funnelDark },
  GearIcon: { light: gearLight, dark: gearDark },
  GitBranchIcon: { light: gitBranchLight, dark: gitBranchDark },
  GitCommitIcon: { light: gitCommitLight, dark: gitCommitDark },
  GitDiffIcon: { light: gitDiffLight, dark: gitDiffDark },
  GitMergeIcon: { light: gitMergeLight, dark: gitMergeDark },
  InfoIcon: { light: infoLight, dark: infoDark },
  KeyboardIcon: { light: keyboardLight, dark: keyboardDark },
  LockIcon: { light: lockLight, dark: lockDark },
  LockOpenIcon: { light: lockOpenLight, dark: lockOpenDark },
  MagnifyingGlassIcon: { light: magnifyingGlassLight, dark: magnifyingGlassDark },
  MinusIcon: { light: minusLight, dark: minusDark },
  OpenExternalIcon: { light: openExternalLight, dark: openExternalDark },
  PauseIcon: { light: pauseLight, dark: pauseDark },
  PencilIcon: { light: pencilLight, dark: pencilDark },
  PlayIcon: { light: playLight, dark: playDark },
  PlusIcon: { light: plusLight, dark: plusDark },
  PushPinIcon: { light: pushPinLight, dark: pushPinDark },
  QuestionIcon: { light: questionLight, dark: questionDark },
  RefreshIcon: { light: refreshLight, dark: refreshDark },
  StopIcon: { light: stopLight, dark: stopDark },
  TrashIcon: { light: trashLight, dark: trashDark },
  UploadIcon: { light: uploadLight, dark: uploadDark },
  UserIcon: { light: userLight, dark: userDark },
  WarningCircleIcon: { light: warningCircleLight, dark: warningCircleDark },
  WarningIcon: { light: warningLight, dark: warningDark },
  XCircleIcon: { light: xCircleLight, dark: xCircleDark },
  XIcon: { light: xLight, dark: xDark },
};
