import LitheCoreContracts

typealias ProjectRunConfigurationStatus = LitheCoreContracts.ProjectRunConfigurationStatus
typealias RunConfigurationRecoveryAction = LitheCoreContracts.RunConfigurationRecoveryAction
typealias RunConfigurationDiagnostic = LitheCoreContracts.RunConfigurationDiagnostic
typealias ProjectRunConfigurationInspection = LitheCoreContracts.ProjectRunConfigurationInspection
typealias RunConfigurationGenerationState = LitheCoreContracts.RunConfigurationGenerationState
typealias RunConfigurationSaveScope = LitheCoreContracts.RunConfigurationSaveScope
typealias RunConfigurationSource = LitheCoreContracts.RunConfigurationSource
typealias EffectiveRunConfiguration = LitheCoreContracts.EffectiveRunConfiguration
typealias RunConfigurationResolution = LitheCoreContracts.RunConfigurationResolution
typealias RunConfigurationOperationFailure = LitheCoreContracts.RunConfigurationOperationFailure
typealias SharedLaunchPlan = LitheCoreContracts.SharedLaunchPlan
typealias RunConfigurationGenerationResult = LitheCoreContracts.RunConfigurationGenerationResult
typealias RunConfigurationDraft = LitheCoreContracts.RunConfigurationDraft
typealias RunConfigurationDocumentMutation = LitheCoreContracts.RunConfigurationDocumentMutation
typealias RunConfigurationDocumentMutating = LitheCoreContracts.RunConfigurationDocumentMutating
typealias ProjectToolchainSelection = LitheCoreContracts.ProjectToolchainSelection
typealias ProjectToolchainCandidate = LitheCoreContracts.ProjectToolchainCandidate
typealias RunConfigurationOperations = LitheCoreContracts.RunConfigurationOperations
