import LitheCoreContracts

typealias WorkspaceFileOperations = LitheCoreContracts.WorkspaceFileOperations

typealias DocumentWriteResult = LitheCoreContracts.DocumentWriteResult
typealias DocumentFileObservation = LitheCoreContracts.DocumentFileObservation
