import LitheCoreContracts

typealias WorkspaceFileOperations = LitheCoreContracts.WorkspaceFileOperations

typealias DocumentWriteResult = LitheCoreContracts.DocumentWriteResult
typealias DocumentFileObservation = LitheCoreContracts.DocumentFileObservation

typealias DocumentEncoding = LitheCoreContracts.DocumentEncoding
typealias DocumentReadDetails = LitheCoreContracts.DocumentReadDetails
typealias EncodedDocumentWriteResult = LitheCoreContracts.EncodedDocumentWriteResult
