import LitheExecutionModule

typealias MavenFeatureModel = LitheExecutionModule.MavenFeatureModel
typealias RunFeatureModel = LitheExecutionModule.RunFeatureModel
typealias ProjectDevelopmentFeatureModel = LitheExecutionModule.ProjectDevelopmentFeatureModel
typealias RunConfigurationGenerationIntent = LitheExecutionModule.RunConfigurationGenerationIntent
typealias JavaRunFeatureModel = LitheExecutionModule.RunFeatureModel
