/**
 * Copies IntelliJ platform icon SVGs into the Lithe icon funnel and emits the
 * generated asset map consumed by `src/ui/icons.tsx`.
 *
 * Usage (run from windows/tauri):
 *   bun scripts/generate-idea-icons.ts --source <intellij-community>/platform/icons/src [--check]
 *
 * The mapping file (scripts/idea-icon-mappings.json) is the single source of
 * truth for which Lithe icon exports use IntelliJ assets; every other export
 * keeps its lucide fallback. Source paths are repo-relative and resolved
 * against --source, so no machine-specific path is persisted. Each copied SVG
 * keeps its embedded Apache-2.0 copyright comment untouched.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

interface MappingEntry {
  icon: string;
  source: string | null;
  note?: string;
}

interface MappingFile {
  icons: MappingEntry[];
}

const REPO_ROOT = resolve(import.meta.dir, "..");
const MAPPING_PATH = join(import.meta.dir, "idea-icon-mappings.json");
const ICONS_TSX_PATH = join(REPO_ROOT, "src/ui/icons.tsx");
const ASSETS_DIR = join(REPO_ROOT, "src/ui/icons/idea");
const GENERATED_TS_PATH = join(REPO_ROOT, "src/ui/icons/idea-assets.generated.ts");

function parseArgs(): { source: string | null; check: boolean } {
  const argv = process.argv.slice(2);
  let source: string | null = null;
  let check = false;
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--source" && argv[i + 1]) {
      source = resolve(argv[i + 1]);
      i += 1;
    } else if (argv[i] === "--check") {
      check = true;
    }
  }
  return { source, check };
}

function toIdentifier(icon: string): string {
  return icon.replace(/Icon$/, "").replace(/^./, (c) => c.toLowerCase());
}

function sha(buffer: Buffer): string {
  return createHash("sha256").update(buffer).digest("hex");
}

const { source: sourceRoot, check } = parseArgs();
if (!sourceRoot) {
  console.error("Missing --source <intellij-community>/platform/icons/src");
  process.exit(1);
}

const mapping = JSON.parse(readFileSync(MAPPING_PATH, "utf8")) as MappingFile;
const iconsTsx = readFileSync(ICONS_TSX_PATH, "utf8");

interface PlannedIcon {
  icon: string;
  source: string;
  light: string;
  dark: string | null;
}

const planned: PlannedIcon[] = [];
const missingSources: string[] = [];
const unknownExports: string[] = [];
const duplicateIcons: string[] = [];

for (const entry of mapping.icons) {
  if (planned.some((p) => p.icon === entry.icon)) {
    duplicateIcons.push(entry.icon);
    continue;
  }
  if (!new RegExp(`export const ${entry.icon} =`).test(iconsTsx)) {
    unknownExports.push(entry.icon);
    continue;
  }
  if (!entry.source) {
    continue;
  }
  const lightAbs = join(sourceRoot, entry.source);
  if (!existsSync(lightAbs)) {
    missingSources.push(entry.source);
    continue;
  }
  const darkRel = entry.source.replace(/\.svg$/, "_dark.svg");
  const darkAbs = join(sourceRoot, darkRel);
  planned.push({
    icon: entry.icon,
    source: entry.source,
    light: entry.source,
    dark: existsSync(darkAbs) ? darkRel : null,
  });
}

planned.sort((a, b) => a.icon.localeCompare(b.icon));

const failures = [
  ...missingSources.map((s) => `source SVG not found: ${s}`),
  ...unknownExports.map((i) => `not exported from src/ui/icons.tsx: ${i}`),
  ...duplicateIcons.map((i) => `duplicate mapping entry: ${i}`),
];
if (failures.length > 0) {
  console.error(failures.join("\n"));
  process.exit(1);
}

let generated = `// AUTO-GENERATED by scripts/generate-idea-icons.ts — do not edit by hand.\n`;
generated += `// Mapping source: scripts/idea-icon-mappings.json (paths relative to the\n`;
generated += `// intellij-community platform/icons/src checkout passed via --source).\n`;
generated += `// Keys are icon export display names resolved by createIconComponent.\n\n`;

for (const p of planned) {
  generated += `import ${toIdentifier(p.icon)}Light from "./idea/${p.light}?url";\n`;
  if (p.dark) {
    generated += `import ${toIdentifier(p.icon)}Dark from "./idea/${p.dark}?url";\n`;
  }
}
generated += `\nexport interface IdeaIconAsset {\n  light: string;\n  dark: string;\n}\n\n`;
generated += `export const ideaIconAssets: Record<string, IdeaIconAsset> = {\n`;
for (const p of planned) {
  const darkId = p.dark ? `${toIdentifier(p.icon)}Dark` : `${toIdentifier(p.icon)}Light`;
  generated += `  ${p.icon}: { light: ${toIdentifier(p.icon)}Light, dark: ${darkId} },\n`;
}
generated += `};\n`;

if (check) {
  const problems: string[] = [];
  if (readFileSync(GENERATED_TS_PATH, "utf8") !== generated) {
    problems.push("src/ui/icons/idea-assets.generated.ts is out of date; rerun the generator");
  }
  for (const p of planned) {
    const pairs = p.dark ? [p.light, p.dark] : [p.light];
    for (const rel of pairs) {
      const copied = join(ASSETS_DIR, rel);
      if (!existsSync(copied)) {
        problems.push(`missing copied asset: src/ui/icons/idea/${rel}`);
      } else if (sha(readFileSync(copied)) !== sha(readFileSync(join(sourceRoot, rel)))) {
        problems.push(`copied asset differs from source: src/ui/icons/idea/${rel}`);
      }
    }
  }
  if (problems.length > 0) {
    console.error(problems.join("\n"));
    process.exit(1);
  }
  console.log(`idea-icons check passed (${planned.length} mapped icons)`);
  process.exit(0);
}

for (const p of planned) {
  const pairs = p.dark ? [p.light, p.dark] : [p.light];
  for (const rel of pairs) {
    const dest = join(ASSETS_DIR, rel);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, readFileSync(join(sourceRoot, rel)));
  }
}
writeFileSync(GENERATED_TS_PATH, generated);
console.log(
  `Copied ${planned.reduce((n, p) => n + (p.dark ? 2 : 1), 0)} SVGs and emitted idea-assets.generated.ts (${planned.length} icons mapped)`,
);
